// For loops and if conditions:

// 5.) [ ] What are all of the words that have no E or A and are at least 15 letters long?

// The Answers:

/* 'BIBLIOPHILISTIC', 'BLOODCURDLINGLY', 'BRONCHOSCOPISTS', 'CHRONOBIOLOGIST',
  'CIRCUMLOCUTIONS', 'CIRCUMPOSITIONS', 'CIRCUMSCRIPTION', 'CIRCUMVOLUTIONS',
  'CITRICULTURISTS', 'CONSCRIPTIONIST', 'CONSTITUTIONIST', 'CONSTRUCTIONISM',
  'CONSTRUCTIONIST', 'CONSTRUCTIVISMS', 'CONSTRUCTIVISTS', 'CONTORTIONISTIC',
  'CORTICOTROPHINS', 'COUNCILLORSHIPS', 'CROSSLINGUISTIC', 'CRYPTORCHIDISMS',
  'CRYPTOSPORIDIUM', 'CRYPTOZOOLOGIST', 'DISCOMMODIOUSLY', 'DISCONTINUOUSLY',
  'DISSOLUTIONISMS', 'DISSOLUTIONISTS', 'FLORICULTURISTS', 'GLUCOCORTICOIDS',
  'HISTOPHYSIOLOGY', 'HORTICULTURISTS', 'HYDROBIOLOGISTS', 'HYDROSULPHUROUS',
  'HYPOPHOSPHOROUS', 'HYPOTHYROIDISMS', 'HYSTRICOMORPHIC', 'IMMUNOBLOTTINGS',
  'IMMUNODIFFUSION', 'IMMUNOGLOBULINS', 'INCONSPICUOUSLY', 'INCORRIGIBILITY',
  'INDISSOLUBILITY', 'INFUNDIBULIFORM', 'INQUISITIONISTS', 'INSTRUCTORSHIPS',
  'LITHONTHRYPTICS', 'LITHONTRIPTISTS', 'LITURGIOLOGISTS', 'MICROBIOLOGISTS',
  'MICROCOMPUTINGS', 'MICROMORPHOLOGY', 'MICROPUBLISHING', 'MICROSPOROPHYLL',
  'MISCONSTRUCTING', 'MISCONSTRUCTION', 'MISDISTRIBUTION', 'MISINSTRUCTIONS',
  'MULTITUDINOUSLY', 'MYRISTICIVOROUS', 'NITROCHLOROFORM', 'NONCOGNITIVISMS',
  'NONCONSTRUCTION', 'NONCONSUMPTIONS', 'NONCONTRIBUTORY', 'NONDISJUNCTIONS',
  'NONPRODUCTIVITY', 'OBSTRUCTIONISMS', 'OBSTRUCTIONISTS', 'ODONTORHYNCHOUS',
  'ONYCHOCRYPTOSIS', 'ORNITHORHYNCHUS', 'ORTHOPHOSPHORIC', 'PHOTOBIOLOGISTS',
  'PHOTOCONDUCTING', 'PHOTOCONDUCTION', 'PHOTOCONDUCTORS', 'PHOTOFINISHINGS',
  'PHOTOINDUCTIONS', 'PHOTOPRODUCTION', 'PISCICULTURISTS', 'POSTPRODUCTIONS',
  'PROHIBITIONISMS', 'PROHIBITIONISTS', 'PROLOCUTORSHIPS', 'PROSTHODONTISTS',
  'PROTISTOLOGISTS', 'PROTOPORPHYRINS', 'PROTOZOOLOGISTS', 'PSYCHOBIOLOGIST',
  'PSYCHOLINGUISTS', 'PSYCHOPHYSICIST', 'PULCHRITUDINOUS', 'PYCNODYSOSTOSIS',
  'PYKNODYSOSTOSIS', 'SHILLINGSWORTHS', 'SILVICULTURISTS', 'SOCIOBIOLOGISTS',
  'SOCIOLINGUISTIC', 'STRONGYLOIDOSIS', 'THOROUGHGOINGLY', 'TRINITROTOLUOLS', */

let fs = require('fs');
fs.readFile('sowpods_for_practice_problems.txt', function(err, data) {
    if (err) throw err;
    let wordsArray = data.toString().split("\n");

    let wordsFoundContainer = [];
    let wordLength = '012345678901234';

    for (word in wordsArray) {
        if (!wordsArray[word].includes('E') && !wordsArray[word].includes('A') && wordsArray[word].length === wordLength.length) {
            wordsFoundContainer.push(wordsArray[word]);
            console.log('Found!');
        } else {
            console.log('Not found!');
        }
    }
    console.log(wordsFoundContainer);
});    